CREATE TABLE IF NOT EXISTS series (id INTEGER PRIMARY KEY, author_id INTEGER, subgenre_id INTEGER, title TEXT);
CREATE TABLE IF NOT EXISTS subgenres (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS authors (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY, series_id INTEGER, year INTEGER, title TEXT);
CREATE TABLE IF NOT EXISTS characters (id INTEGER PRIMARY KEY, author_id INTEGER, motto TEXT, species TEXT, name TEXT);
CREATE TABLE IF NOT EXISTS character_books (id INTEGER PRIMARY KEY, book_id INTEGER, character_id INTEGER);